# source code for probing and setting lcd pins
SRC = lcd-pin-config.c

# Target Binary
BIN = lcd-pin-config

lcd-pin-config:
	$(CC) $(CFLAGS) $(LDFLAGS) -o lcd-pin-config $(SRC) -I. -Wall -Os

clean:
	rm -rf lcd-pin-config

